NUMPY Package explained

In [2]:
#import package
import numpy as np

In [6]:
#1D array
a=np.array([1,2,3])
#2D array
b=np.array([(1.5,2,3),(4,5,6)],dtype=float)
#3D array
c=np.array([[(1.5,2,3),(4,5,6)],[(3,2,1),(4,5,6)]],dtype=float)
print(a)
print(b)
print(c)

[1 2 3]
[[1.5 2.  3. ]
 [4.  5.  6. ]]
[[[1.5 2.  3. ]
  [4.  5.  6. ]]

 [[3.  2.  1. ]
  [4.  5.  6. ]]]


><b>np.zeros((3,4))</b> Create an array of zeros<br>
><b>np.ones((2,3,4),dtype=np.int16)</b> Create an array of ones<br>
><b>d = np.arange(10,25,5)</b> Create an array of evenly
spaced values (step value)<br>
><b>np.linspace(0,2,9)</b> Create an array of evenly
spaced values (number of samples)<br>
><b>e = np.full((2,2),7)</b> Create a constant array<br>
><b>f = np.eye(2)</b> Create a 2X2 identity matrix<br>
><b>np.random.random((2,2))</b> Create an array with random values<br>
><b>np.empty((3,2))</b> Create an empty array

#saving and loading
np.save('my_array', a)
np.savez('array.npz', a, b)
np.load('my_array.npy')

<b> DATA TYPES</b>

np.int64 Signed 64-bit integer types<br>
np.float32 Standard double-precision floating point<br>
np.complex Complex numbers represented by 128 floats<br>
np.bool Boolean type storing TRUE and FALSE values<br>
np.object Python object type<br>
np.string_ Fixed-length string type<br>
np.unicode_ Fixed-length unicode type

<b> Inspecting array</b>

In [13]:
#np.info(np.ndarray.dtype)
#a.shape
#len(a)
#b.ndim
#b.size
#b.dtype
#b.dtype.name
b=b.astype(int)

In [14]:
b.dtype

dtype('int32')

<img src='npcal.PNG'/>

In [16]:
a.mean()

2.0

<b>Copying arrays</b>

In [19]:
h=a.view()
np.copy(a)
h=a.copy()


In [20]:
h

array([1, 2, 3])

<b>Sorting arrays</b>

In [25]:
a.sort()
c.sort(axis=0)

In [26]:
c

array([[[1.5, 2. , 1. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 3. ],
        [4. , 5. , 6. ]]])

<img src='subsetarray.PNG'/>